--- # This is the playbook for TOTUS configuration
  
- hosts: 35.178.230.218
  gather_facts: no
  connection: ssh
  remote_user: root
  become: True

  tasks:

  # This task create groups
  - name: Ensure group admins is present
    group: name=admins state=present
    sudo: yes

  # This task creates users
  - name: Create users accounts and add users to groups
    user:
      name: cdudu
      password: "*"
      groups: admins
      append: yes
      shell: /bin/bash
      home: /home/cdudu

      name: akiss
      password: "*"
      groups: admins
      append: yes
      shell: /bin/bash
      home: /home/akiss

      name: gsikorski
      password: "*"
      groups: admins
      append: yes
      home: /home/gsikorski

  # This task add public keys for user account
  - name: make directory
    file:
      path: /home/cdudu/.ssh
      state: directory
      mode: 0700
      owner: cdudu
      group: cdudu
  - name: create empty file
    file:
      path: /home/cdudu/.ssh/authorized_keys
      state: touch
  - name: put pubkey
    lineinfile:
      path: /home/cdudu/.ssh/authorized_keys
      mode: 0700
      owner: cdudu
      group: cdudu
      line: 
 
  - name: make directory
    file:
      path: /home/akiss/.ssh
      state: directory
      mode: 0700
      owner: akiss
      group: akiss
  - name: create empty file
    file:
      path: /home/akiss/.ssh/authorized_keys
      state: touch
  - name: put pubkey
    lineinfile:
      path: /home/akiss/.ssh/authorized_keys
      mode: 0700
      owner: akiss
      group: akiss
      line:

  - name: make directory
    file:
      path: /home/gsikorski/.ssh
      state: directory
      mode: 0700
      owner: gsikorski
      group: gsikorski
  - name: create empty file
    file:
      path: /home/gsikorski/.ssh/authorized_keys
      state: touch
  - name: put pubkey
    lineinfile:
      path: /home/gsikorski/.ssh/authorized_keys
      mode: 0700
      owner: gsikorski
      group: gsikorski
      line: 

  # This task allow ‘admins’ group to have passwordless sudo lineinfile:
  - name: Allow 'admins' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      regexp: '^%admins'
      line: '%admins ALL=(ALL) NOPASSWD: ALL'
